# Generated by Django 5.1.6 on 2025-02-25 04:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('40-Shots', '40 shots'), ('60-Shots', '60 shots')], max_length=10)),
                ('series_1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10)),
                ('series_2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10)),
                ('series_3', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10)),
                ('series_4', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10)),
                ('series_5', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10)),
                ('series_6', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=10)),
                ('s1t', models.IntegerField(editable=False, null=True)),
                ('s2t', models.IntegerField(editable=False, null=True)),
                ('s3t', models.IntegerField(editable=False, null=True)),
                ('s4t', models.IntegerField(editable=False, null=True)),
                ('s5t', models.IntegerField(editable=False, null=True)),
                ('s6t', models.IntegerField(editable=False, null=True)),
                ('average', models.FloatField(editable=False, null=True)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
