# Generated by Django 5.1.6 on 2025-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='adjustment_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='adjustment_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
