# Generated by Django 5.1.6 on 2025-02-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_score_adjustment_comment_score_adjustment_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='day',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
