# Generated by Django 5.1.6 on 2025-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_pdfscore_gps_pdfscore_gps1_pdfscore_gps2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfscore',
            name='gps',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='gps1',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='gps2',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='gps3',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='gps4',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='gps5',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='gps6',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
