# Generated by Django 5.1.6 on 2025-03-03 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_pdfscore_gps_alter_pdfscore_gps1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfscore',
            name='s1mpi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='s2mpi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='s3mpi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='s4mpi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='s5mpi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='pdfscore',
            name='s6mpi',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), blank=True, null=True, size=2),
        ),
    ]
