# Generated by Django 5.1.6 on 2025-02-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_date_score_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
