# Generated by Django 5.1.6 on 2025-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_score_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
