# Generated by Django 5.1.6 on 2025-03-05 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_alter_pdfscore_fmpi_alter_pdfscore_s1mpi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_category', models.CharField(max_length=150)),
                ('activity_name', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('Notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
