# Generated by Django 5.1.6 on 2025-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='role',
            field=models.CharField(default='Shooter', max_length=150),
            preserve_default=False,
        ),
    ]
