# Generated by Django 5.1.6 on 2025-03-13 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachshooterrelation',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shooters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachshooterrelation',
            name='shooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='coach',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_shooters', to=settings.AUTH_USER_MODEL),
        ),
    ]
