# Generated by Django 5.1.6 on 2025-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofiles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='role',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Coach', 'Coach'), ('Admin', 'Admin')], default='Shooter', max_length=150),
        ),
    ]
