# Generated by Django 5.1.6 on 2025-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_coachshooterrelation_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachshooterrelation',
            name='accepting_shooters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coachshooterrelation',
            name='max_shooters',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
