# Generated by Django 5.1.6 on 2025-02-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofiles_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofiles',
            old_name='Last_Name',
            new_name='last_name',
        ),
    ]
