# Generated by Django 5.1.6 on 2025-03-17 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coachshooterrelation_accepting_shooters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('activity', models.CharField(max_length=255)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_planner', to=settings.AUTH_USER_MODEL)),
                ('shooter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shooter_planner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
