# Generated by Django 5.1.6 on 2025-03-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dayplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanner',
            name='shared_with_shooter',
            field=models.BooleanField(default=False),
        ),
    ]
