# Generated by Django 5.1.6 on 2025-03-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofiles_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='coaching_specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
