# Generated by Django 5.1.6 on 2025-03-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofiles_affiliated_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
