# Generated by Django 5.1.6 on 2025-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofiles_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='category',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
