# Generated by Django 5.1.6 on 2025-03-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofiles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='permitted',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
    ]
