# Generated by Django 5.1.6 on 2025-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofiles_permitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='role',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Coach', 'Coach'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Shooter', max_length=150),
        ),
    ]
