# Generated by Django 5.1.6 on 2025-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofiles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
